# Generated by Django 2.1.7 on 2019-03-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_faculty_faculty_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='emp_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
