# Generated by Django 2.1.7 on 2019-03-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20190227_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='working_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='working_hrs',
            field=models.IntegerField(default=0),
        ),
    ]
