# Generated by Django 2.1.7 on 2019-03-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeTable', '0002_auto_20190303_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time_table',
            old_name='day',
            new_name='days',
        ),
    ]
